const user_data = [{
    email: "lethanhviet@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$V1jAu/3HNMfwZtglX/cIWeSCC5c.TdD5DNbKBhnpT8fNZSoT9H3zq",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$.AZaZEJYMb6RoyWd2e6nnu7zLtdjDBvsPh2ZKSxjWyNeKayiSIuTO",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$SsrMARwOZQrKPzHW8m98POpponroVL7paSAOlgxsjXKcQD6nFa8ja",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$bsjPRJi8ffjGkFwNW.tFdueCyE/dhfwZLZnkksE4j4zNp/DWqdRcS",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$jr7WUFYSiLTQFCCj4B07juS8zVO/5FowRxEfVOzWrQ.WXjRqS7lse",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$GA04eMQFQM4wGan4/GqKHeEsK.zo/pkYMZvNf93r1Cxrl6nk9Fci6",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$n8xPTrCgzd5rZTRoiA8DxOz8JNJdPgly/xyLYeR2r1NWYsn8gsJZa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$CxWIg6pz9CEhSkiPIzBPc.rasGX3rkBbiHBf93faMgky7.AE8lxeK",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$074w/cGELvGdh9UjjeiOXuYfuHC692BBznhcwCEy2./IwSkgFU1Zm",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$gaF5nvAkRAidOJSVQ5Q6GuW.vUsRlsVem8aI50fbtP94HS/wZe.ni",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$4g.UqmdO6J7ZLN2CuKWL0ew5tJzke5Rg2e0p5WjrjoiRrS3ihdvma",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$LU6/U0c7N1.6FB13.t1uveboCA3CKuMFymKgbJXmCpipy43r0Y.Iq",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$WwCMbJfnv9bITwAb2ibnJ.xEp37kAUzT2aQEpmiM8qDqNs91xNp.O",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$iDdpW.dzqzbV5B5glszhUesu5SG4robO40JmbiZFhIur8d3gzefim",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet1@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$lO1uF7DwriEa/GcRvcUcXuPyN7D1cLzm8CVRRx7jp/uFp5rhUBliS",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh1@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$nkIAif5nkULprjqA7wDAj.RmKhX7ifZXIphuEqRn2v2IKeS/a6ZUy",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong1@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$E9qYfgiN7A1/2e4OJpZhSuPL8dO4B45sPxZF7gftLKsT/ZyWvtiWC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy1@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$lXTFqzYxk3Whia//gNgIVOGArSMKned84fopI9Pr0abQMYpIBRzoC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong1@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$mR6iqNZ.RpDg82AJbCNcc.ibCkrOcxbFEM9RWfnVDqFQMz1w1HIya",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung1@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$H0mYU.DaOX8IJoMxXnmmNObQtN7VsMrPJjDBCdXBcYXSFy4rsuLIC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh1@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$.8Pq0I4J.oyPqZFfVPqUr.w938hzJvMgHj5pdaB.36ErWyDhWIe7m",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen1@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$xuPi05oEOZHv/dOlFPnieu.sNYAZ6PkSeDe.e2aE2zMVp4p79d3WC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi1@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$pGHzG9u5aIHb4cohGSLtCeoS4v5MdXHCAyYuGzfNsIj5uvnK0pFMi",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan1@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$DwX2ZwhJdYMia2TPM3WVAOfCDXifEsC2xMpWtLzy2/cEpWWeh8d7q",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy1@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$sKpDFgI9N0KfMa24kQNvP.oopa0C6nrsZW1A74rSrIccB/nM4T0hS",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi1@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$QX0Ugd..8YVkRRhNAMYeie0D/SYEIuaP7GRRiF6fNFfEe2SKwId32",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan1@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$OTPKkDGbcSL1/WW/9k6D2OoF8gtcF/uILMKNOizhBbF0D4ZzMpbiO",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh1@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$fKiyfZviWMkfWT/7rIR/z.5s9Abj2d/haL4SOIrLT3NBaPImAaSPe",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet2@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$VeaWctGcLeTN18p9Lba2X.rAMYf0l7lbEMq0yY8BX7lxjRZPUBGJe",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh2@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong2@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy2@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong2@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung2@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh2@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen2@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi2@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan2@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy2@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi2@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan2@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh2@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet3@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh3@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong3@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy3@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong3@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung3@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh3@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen3@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi3@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan3@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy3@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi3@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan3@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh3@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet4@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh4@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong4@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy4@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong4@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung4@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh4@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen4@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi4@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan4@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy4@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi4@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan4@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh4@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet5@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh5@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong5@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy5@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong5@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung5@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh5@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen5@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi5@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan5@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy5@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi5@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan5@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh5@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}];

const course_data = [
    {
        name: 'NodeJS cho người mới bắt đầu',
        category: 'Lập trình Web',
        chapters: [
            {
                title: 'Bài 1: Giới thiệu những kiến thức cơ bản về NodeJS',
                video: '/courses/temp/0.mp4',
            },
            {
                title: 'Bài 2: NPM và Package',
                video: '/courses/temp/1.mp4',
            },
            {
                title: 'Bài 3: Install and Uninstall package',
                video: '/courses/temp/2.mp4',
            },
        ],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,20),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản nhất cho người mới học NodeJS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0.2,
        thumbnail: '/images/courses_thumbnail/1.jpg',
        description: `NodeJS là một mã nguồn mở, được dùng để xây dựng các ứng dụng mạng, đặc biệt các ứng đòi hỏi real time (thời gian thực) & khối lượng request lớn. Chúng ta có thể lập trình NodeJS với ngôn ngữ JavaScript. NodeJS có thể được dùng để xây dựng hoàn chỉnh một trang web, ngoài ra, NodeJS còn có thể tích hợp để xây dựng các ứng dụng real time trên iOS, Android, Game online với Unity, Cocos2dx.
                Về tốc độ thực thi, Node.js có thể nói là nhanh nhất hiện nay, hơn cả java. Bởi lẽ node.js kế thừa công nghệ V8 của google, khả năng tự build server bằng ngôn ngữ client giúp cho việc trung chuyển dữ liệu diễn ra nhanh hơn. Đồng thời giảm khả năng rủi ro bị ngắt (interupt). Ngoài ra nhờ cơ chế Non I/O Blocking, tận dụng tối đa tài nguyên của server, không tạo ra độ trễ như các ngôn ngữ phía server khác.
                NodeJS thực sự tỏa sáng trong việc xây dựng RESTful API (JSON). Gần như không có ngôn ngữ nào xử lý JSON dễ dàng hơn Javascript, chưa kể các API server thường không phải thực hiện những xử lý nặng nề nhưng lượng concurrent request thì rất cao. Mà Node.js thì xử lý non-blocking. Chẳng còn gì thích hợp hơn Node.js trong trường hợp này!
                NodeJS sinh ra là để xây dựng các ứng dụng thời gian thực (Real time) như ứng dụng chat, các dịch vụ mạng xã hội như Facebook, Twitter,…
                Đối với thiết kế web: NodeJS xử lý mọi request trên cùng một process giúp cho việc xây dựng các bộ nhớ đệm chưa bao giờ đơn giản đến thế: Node.js có thể handle hàng nghìn kết nối đồng thời với chi phí tối thiểu trên 1 quá trình duy nhất.
                NodeJS sử dụng ngôn ngữ JavaScript - một ngôn ngữ phổ biến, và chính điều này đã giúp node.js trở nên quen thuộc và dễ dàng được áp dụng rộng rãi hơn.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Sau khi kết thúc khóa học bạn sẽ có những kiến thức cơ bản nhất về NodeJS, đủ kiến thức để xây dựng những web thương mại điện tử bằng NodeJS và ứng tuyển thực tập về NodeJS ở các công ty.',
    },{
        name: 'Khóa học Full-stack web developer',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,19),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học bao gồm nhiều kỹ năng cả về FE và BE : HTML, CSS, JS, NodeJS, AngularJS,...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/2.jpg',
        description: `Khóa học cung cấp những kiến thức và nền tảng cơ bản nhất cả về Front-end lẫn Back-end cho học viên.
         Về front-end, các bạn sẽ được học cơ bản từ HTML, CSS, responsive,... tiếp đến là JS và ES6,ES7, ES2020,...
         Ngoài ra khóa học còn cung cấp kiến thức về các frameword của JavaScript như ReactJS, AngularJS, VueJS hỗ trợ
         lập trình về client-side. Về Back-end, các bạn sẽ được học cách tạo server, sử dụng CSDL, deploy, CICD,...Trong khóa học này
         chúng ta sẽ sử dụng NodeJS ở server-side và Express là chủ yếu, về Cơ sở dũ liệu, bạn học sẽ được hướng dẫn sử dụng MySQL,
         và No-SQL MongoDB. Ngoài ra khóa học cũng sẽ hướng dẫn hoàn thành một Project hoàn chỉnh về một trang thương mại điện tử, đồng
         thời cũng hướng dẫn bạn học deploy website của mình lên Heroku.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: `Sau khi kết thúc khóa học các bạn sẽ có một nền tảng vững chắc để trở thành một Full-stack developer.
        Có đầy đủ kiến thức về Front-end và Back-end để ứng tuyển thực tập ở các công ty.`,
    },{
        name: 'Khóa học NodeJS chuyên sâu',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,17),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học chuyên sâu về SSR với NodeJS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/3.jpg',
        description: `NodeJS là một mã nguồn mở, được dùng để xây dựng các ứng dụng mạng, đặc biệt các ứng đòi hỏi real time (thời gian thực) & khối lượng request lớn. Chúng ta có thể lập trình NodeJS với ngôn ngữ JavaScript. NodeJS có thể được dùng để xây dựng hoàn chỉnh một trang web, ngoài ra, NodeJS còn có thể tích hợp để xây dựng các ứng dụng real time trên iOS, Android, Game online với Unity, Cocos2dx.
        Về tốc độ thực thi, Node.js có thể nói là nhanh nhất hiện nay, hơn cả java. Bởi lẽ node.js kế thừa công nghệ V8 của google, khả năng tự build server bằng ngôn ngữ client giúp cho việc trung chuyển dữ liệu diễn ra nhanh hơn. Đồng thời giảm khả năng rủi ro bị ngắt (interupt). Ngoài ra nhờ cơ chế Non I/O Blocking, tận dụng tối đa tài nguyên của server, không tạo ra độ trễ như các ngôn ngữ phía server khác.
        NodeJS thực sự tỏa sáng trong việc xây dựng RESTful API (JSON). Gần như không có ngôn ngữ nào xử lý JSON dễ dàng hơn Javascript, chưa kể các API server thường không phải thực hiện những xử lý nặng nề nhưng lượng concurrent request thì rất cao. Mà Node.js thì xử lý non-blocking. Chẳng còn gì thích hợp hơn Node.js trong trường hợp này!
        NodeJS sinh ra là để xây dựng các ứng dụng thời gian thực (Real time) như ứng dụng chat, các dịch vụ mạng xã hội như Facebook, Twitter,…
        Đối với thiết kế web: NodeJS xử lý mọi request trên cùng một process giúp cho việc xây dựng các bộ nhớ đệm chưa bao giờ đơn giản đến thế: Node.js có thể handle hàng nghìn kết nối đồng thời với chi phí tối thiểu trên 1 quá trình duy nhất.
        NodeJS sử dụng ngôn ngữ JavaScript - một ngôn ngữ phổ biến, và chính điều này đã giúp node.js trở nên quen thuộc và dễ dàng được áp dụng rộng rãi hơn.
        Đây là khóa học nối tiếp của khóa học NodeJS cho người mới bắt đầu, sau khi đã có những kiến thức cơ bản 
        chúng ta sẽ tiếp tục tìm hiểu những kiến thức nâng cao hơn về NodeJS. Trong khóa học này bạn sẽ được học về Filesystem,
         Module, Deloy, Authentication,...`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Hoàn thiện và nâng cao kiến thức về NodeJS',
    },{
        name: 'Khóa học MERN: MongoDB, Express, ReactJS, NodeJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học full-stack với MongoDB database và các framework của JS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/4.jpg',
        description: `Khóa học full-stack với MongoDB database và các framework của JS. Trong khóa học này, bạn học sẽ được cung
        cấp những kiến thức cần thiết để tạo một website thương mại điện tử  với MERN: M - MongoBD, E - Express, R - ReacJS, N - NodeJS.
        Khóa học sẽ hướng dẫn bạn sử dụng NodeJS + Express để tạo một server và chạy trên chính máy tính của mình; sử dụng ReactJS để 
        code giao diện ở client-side, bên cạnh kiến thức cơ bản về React như Component, Router, ... khóa học còn cung cấp kiến thức về 
        Hook, Redux,...; cơ sở dữ liệu được dùng trong khóa học này như đã đề cập ở trên chính là MongoDB - một No-SQL.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Hiểu biết về 4 thành phần của MEAN, có khả năng tự lập trình các website sử dụng những kiến thức đã học.',
    },{
        name: 'Khóa học MEAN: MongoDB, Express, AngularJS, NodeJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học full-stack với MongoDB database và các framework của JS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/5.png',
        description: `Khóa học full-stack với MongoDB database và các framework của JS. Trong khóa học này, bạn học sẽ được cung
        cấp những kiến thức cần thiết để tạo một website thương mại điện tử  với MERN: M - MongoBD, E - Express, R - ReacJS, N - NodeJS.
        Khóa học sẽ hướng dẫn bạn sử dụng NodeJS + Express để tạo một server và chạy trên chính máy tính của mình; sử dụng ReactJS để 
        code giao diện ở client-side, bên cạnh kiến thức cơ bản về React như Component, Router, ... khóa học còn cung cấp kiến thức về 
        Hook, Redux,...; cơ sở dữ liệu được dùng trong khóa học này như đã đề cập ở trên chính là MongoDB - một No-SQL.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Hiểu biết về 4 thành phần của MEAN, có khả năng tự lập trình các website sử dụng những kiến thức đã học.',
    },{
        name: 'Javascript Framework: ReactJS and AngularJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản và đầy đủ về 2 framework phổ biến của JS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/6.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học GraphQL',
        category: 'Hệ thống thông tin',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học về cơ sở GraphQL và tích hợp SSR',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/7.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học lập trình Web cơ bản',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản về HTML, CSS, JavaScript,...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/8.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học ExpressJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Express là một framework của JS sử dụng ở SS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/9.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học React cơ bản',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản về React: Component, Router, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/10.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Javascript cơ bản',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản về JS: ES5, ES6, variable, operations, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/11.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Javascript nâng cao',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học nâng cao về JS: hoisting, scope, promise, async await, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/12.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Javascript ES6',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học về JS phiên bản ES6: let, arrow function, spread operator, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/13.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học NuxtJS',
        category: 'Hệ thống thông tin',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học dành cho người mới bắt đầu về framework NuxtJS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/14.jpeg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Lập trình web với NodeJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Lập trình SS với NodeJS nâng cao',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/15.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },
]

const category_data = [
    {
        name: 'Công nghệ thông tin',
        parent: 'null',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Toán học',
        parent: 'null',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Lập trình Web',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Lập trình ứng dụng di động',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Khoa học máy tính',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Hệ thống thông tin',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Toán tổ hợp',
        parent: 'Toán học',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Toán rời rạc',
        parent: 'Toán học',
        courses: '',
        soldInWeek: 0
    },

    {
        name: 'Xác suất thống kê',
        parent: 'Toán học',
        courses: '',
        soldInWeek: 0
    }
]

const teacher_data = [{
    email: 'nguyenvantu5@gmail.com',
    name: 'Nguyễn Văn Tú',
    bthday: new Date('1976-05-21'),
    password: '$2b$10$Fd0GDCRSSwpzsUaaAzSrz.tLxvBIWWX4G1WwRmekSvK7UdrS94z7a',
    courses: [],
    userType: 'Teacher',
    phone: '+84-555-527-787',
    gender: 'Nam',
    shortBio: `<p>Hiện tại đang l&agrave; Gi&aacute;m Đốc Điều H&agrave;nh Navigos Search thuộc tập đo&agrave;n Navigos<br />Hơn 25 năm kinh nghiệm, trong đ&oacute; c&oacute; 20 năm trong lĩnh vực ph&aacute;t triển kinh doanh v&agrave; điều h&agrave;nh doanh nghiệp với gần 10 năm trong lĩnh vực Nh&acirc;n sự. <br />Trước khi gia nhập Navigos, chị đươc biết đến với c&aacute;c vai tr&ograve;:<br />Trưởng văn ph&ograve;ng đại diện đầu ti&ecirc;n tại Việt Nam của Hiệp hội kế to&aacute;n c&ocirc;ng chứng Anh Quốc ACCA<br />Gi&aacute;m đốc ph&aacute;t triển kinh doanh của Deloitte Việt Nam<br />Tổng gi&aacute;m đốc của eSillicon Việt Nam</p>`,
  }, {
    email: 'trantanthanh2@gmail.com',
    name: 'Trần Tấn Thành',
    bthday: new Date('1979-08-08'),
    password: '$2b$10$gzYEFuBiuRsv51yy9zxRZur.mbAPN7DBBLHRSZwY4aEhyTwJl/9iW',
    courses: [],
    userType: 'Teacher',
    phone: '+84-555-515-816',
    gender: 'Nam',
    shortBio: '<p>- CEO Học viện Marketing Quốc tế TikTokVIP<br />- 5 năm kinh nghiệm l&agrave;m việc tại thị trường c&ocirc;ng nghệ Trung Quốc<br />- Được đ&agrave;o tạo chuy&ecirc;n s&acirc;u từ Douyin Trung Quốc trong 3 năm (Dou</p>',
  }, {
    email: 'phamnguyencongminh@gmail.com',
    name: 'Phạm Nguyễn Công Minh',
    bthday: new Date('1979-11-01'),
    password: '$2b$10$qk7zGEBjc1uNHtgg8.qcQO6ezLLJ85awi6b6cB6G3L3YTp4Uwzfnq',
    courses: [],
    userType: 'Teacher',
    phone: '+84-355-510-723',
    gender: 'Nam',
    shortBio: '<h2>Th&ocirc;ng tin Giảng vi&ecirc;n</h2><p>Chuy&ecirc;n gia đ&agrave;o tạo, tư vấn v&agrave; triển khai giải ph&aacute;p về E-Commerce, E-Business, E-Marketing</p><h3>Học vấn:</h3><p>- Thạc sỹ quản trị kinh doanh quốc tế (MBA) chuy&ecirc;n ng&agrave;nh Business &amp; Marketing &ndash; Đại học Nice &ndash; Sofia Antipolis (2012)</p>',
  }, {
    email: 'tranlecongluat@gmail.com',
    name: 'Trần Lê Công Luật',
    bthday: new Date('1984-01-19'),
    password: '$2b$10$FHwKig1gVky2zPmFtiXcsOnYf25BLnarl/NPQC6aDJN8LfbY3SlXS',
    courses: [],
    userType: 'Teacher',
    phone: '+84-355-548-131',
    gender: 'Nam',
    shortBio: '<p><strong>Founder Học Viện PAcademy, Trung T&acirc;m Đ&agrave;o Tạo Digital Marketing Thực Chiến</strong></p><p>- Quản Trị Vi&ecirc;n Cộng đồng Kinh doanh PGroup. Hỗ trợ c&aacute;c th&agrave;nh vi&ecirc;n triển khai đồng bộ Hệ thống k&ecirc;nh Marketing Online với m&ocirc; h&igrave;nh Kinh doanh mới nhất</p><p>- Kinh nghiệm chạy quảng c&aacute;o Facebook kết hợp c&aacute;c trang thương mại điện tử đa k&ecirc;nh Zalo, Instagram, Youtube...với số tiền đ&atilde; chi ti&ecirc;u hơn 20 tỷ VNĐ</p><p>- Kinh Doanh Online Thương mại điện tử c&aacute;c ng&agrave;nh h&agrave;ng: Gia dụng th&ocirc;ng minh, Thời trang, Giảm c&acirc;n, Tăng c&acirc;n, Mẹ b&eacute;, Mỹ phẩm, Dụng cụ thể dục thể thao, ...</p><p>- Ph&oacute; GĐ Ph&aacute;t triển Kinh doanh tại Jews Academy - Tổ hợp nh&agrave; h&agrave;ng, sự kiện.</p><p>- Tư&nbsp; vấn x&acirc;y dựng Fanpage, x&acirc;y dựng k&ecirc;nh Marketing Online cho h&agrave;ng trăm Shop online: thời trang, du lịch, ẩm thực, đồng hồ c&ocirc;ng nghệ,....</p><p>- Giảng vi&ecirc;n tr&ecirc;n c&aacute;c hệ thống gi&aacute;o dục trực tuyến h&agrave;ng đầu Việt Nam với số lượng học vi&ecirc;n đ&ocirc;ng đảo</p><p>&nbsp;</p><p>Phương ch&acirc;m: Chia sẻ chứ kh&ocirc;ng Dạy học, Quan điểm Kinh doanh cần xuất ph&aacute;t từ gốc rễ (chọn lựa sản phẩm ph&ugrave; hợp, nghi&ecirc;n cứu đối thủ, nghi&ecirc;n cứu kh&aacute;ch h&agrave;ng mục ti&ecirc;u, thiết lập v&agrave; tối ưu quảng c&aacute;o...). X&acirc;y dựng từ những điều cốt l&otilde;i, v&agrave; từng bước chi tiết gi&uacute;p bạn x&acirc;y dựng Hệ thống Kinh doanh b&agrave;i bản.</p>',
  }, {
    email: 'nguyenletuananh@gmail.com',
    name: 'Nguyên Lê Tuấn Anh',
    bthday: null,
    password: '$2b$10$S9Cmb4KBjjXWkoqHNIz9NeI7H7gu0e/LwsyF94Gv2t0xptdbw9naS',
    courses: [],
    userType: 'Teacher',
    phone: '+84-955-559-959',
    gender: 'Nam',
    shortBio: '<p>Hiện tại đang l&agrave; Gi&aacute;m Đốc Điều H&agrave;nh Navigos Search thuộc tập đo&agrave;n Navigos<br />Hơn 25 năm kinh nghiệm, trong đ&oacute; c&oacute; 20 năm trong lĩnh vực ph&aacute;t triển kinh doanh v&agrave; điều h&agrave;nh doanh nghiệp với gần 10 năm trong lĩnh vực Nh&acirc;n sự. <br />Trước khi gia nhập Navigos, chị đươc biết đến với c&aacute;c vai tr&ograve;:<br />Trưởng văn ph&ograve;ng đại diện đầu ti&ecirc;n tại Việt Nam của Hiệp hội kế to&aacute;n c&ocirc;ng chứng Anh Quốc ACCA<br />Gi&aacute;m đốc ph&aacute;t triển kinh doanh của Deloitte Việt Nam<br />Tổng gi&aacute;m đốc của eSillicon Việt Nam</p>',
  }, {
    email: 'lethanhbinh@gmail.com',
    name: 'Lê Thanh Bình',
    bthday: new Date('1992-02-20'),
    password: '$2b$10$QC2iZAwoXFUIUb/a/OK0nOmF/FPeUoizQ5QohngAvfzypGhNSUmSO',
    courses: [],
    userType: 'Teacher',
    phone: '+84-855-509-460',
    gender: 'Nam',
    shortBio: '<h2>Th&ocirc;ng tin Giảng vi&ecirc;n</h2><p>Chuy&ecirc;n gia đ&agrave;o tạo, tư vấn v&agrave; triển khai giải ph&aacute;p về E-Commerce, E-Business, E-Marketing</p><h3>Học vấn:</h3><p>- Thạc sỹ quản trị kinh doanh quốc tế (MBA) chuy&ecirc;n ng&agrave;nh Business &amp; Marketing &ndash; Đại học Nice &ndash; Sofia Antipolis (2012)</p>',
  }, {
    email: 'phamtandung@gmail.com',
    name: 'Phạm Tấn Dũng',
    bthday: new Date('1977-02-01'),
    password: '$2b$10$N3Z0kfgwW82xC7Vl8DxfN.WnJ8JwmeJmVmm3TyQREwMNUcUba1OG.',
    courses: [],
    userType: 'Teacher',
    phone: '+84-555-534-391',
    gender: 'Nam',
    shortBio: '<p><strong>Chức vụ:</strong></p><p>Nguy&ecirc;n gi&aacute;m đốc Chiến lược C&ocirc;ng ty Chứng kho&aacute;n Mirea Asset (H&agrave;n Quốc)</p><p><strong>Học vấn:&nbsp;</strong></p><p>Thạc sỹ Quản trị kinh doanh&nbsp;</p><p><strong>Kinh nghiệm:</strong></p><p>2006 - 2016: Giảng vi&ecirc;n Giảng dạy Ph&acirc;n t&iacute;ch Kỹ thuật tại Vietway Edu</p><p>2012 - 2014:&nbsp;Trưởng ph&ograve;ng đầu tư quỹ ASHAHI</p>',
  }, {
    email: 'tranphutrong@gmail.com',
    name: 'Trần Phú Trọng',
    bthday: new Date('1978-12-13'),
    password: '$2b$10$k6RGJS0f5GIZVHwVTkokRuhGpGuG9dEGPNX9knxhHAQ6QV2mvkYmi',
    courses: [],
    userType: 'Teacher',
    phone: '+84-555-539-007',
    gender: 'Nam',
    shortBio: '<p><strong>Founder Học Viện PAcademy, Trung T&acirc;m Đ&agrave;o Tạo Digital Marketing Thực Chiến</strong></p><p>- Quản Trị Vi&ecirc;n Cộng đồng Kinh doanh PGroup. Hỗ trợ c&aacute;c th&agrave;nh vi&ecirc;n triển khai đồng bộ Hệ thống k&ecirc;nh Marketing Online với m&ocirc; h&igrave;nh Kinh doanh mới nhất</p><p>- Kinh nghiệm chạy quảng c&aacute;o Facebook kết hợp c&aacute;c trang thương mại điện tử đa k&ecirc;nh Zalo, Instagram, Youtube...với số tiền đ&atilde; chi ti&ecirc;u hơn 20 tỷ VNĐ</p><p>- Kinh Doanh Online Thương mại điện tử c&aacute;c ng&agrave;nh h&agrave;ng: Gia dụng th&ocirc;ng minh, Thời trang, Giảm c&acirc;n, Tăng c&acirc;n, Mẹ b&eacute;, Mỹ phẩm, Dụng cụ thể dục thể thao, ...</p><p>- Ph&oacute; GĐ Ph&aacute;t triển Kinh doanh tại Jews Academy - Tổ hợp nh&agrave; h&agrave;ng, sự kiện.</p><p>- Tư&nbsp; vấn x&acirc;y dựng Fanpage, x&acirc;y dựng k&ecirc;nh Marketing Online cho h&agrave;ng trăm Shop online: thời trang, du lịch, ẩm thực, đồng hồ c&ocirc;ng nghệ,....</p><p>- Giảng vi&ecirc;n tr&ecirc;n c&aacute;c hệ thống gi&aacute;o dục trực tuyến h&agrave;ng đầu Việt Nam với số lượng học vi&ecirc;n đ&ocirc;ng đảo</p><p>&nbsp;</p><p>Phương ch&acirc;m: Chia sẻ chứ kh&ocirc;ng Dạy học, Quan điểm Kinh doanh cần xuất ph&aacute;t từ gốc rễ (chọn lựa sản phẩm ph&ugrave; hợp, nghi&ecirc;n cứu đối thủ, nghi&ecirc;n cứu kh&aacute;ch h&agrave;ng mục ti&ecirc;u, thiết lập v&agrave; tối ưu quảng c&aacute;o...). X&acirc;y dựng từ những điều cốt l&otilde;i, v&agrave; từng bước chi tiết gi&uacute;p bạn x&acirc;y dựng Hệ thống Kinh doanh b&agrave;i bản.</p>',
  }, {
    email: 'nguyentrankimngan@gmail.com',
    name: 'Nguyễn Trần Kim Ngân',
    bthday: new Date('1990-04-30'),
    password: '$2b$10$nYYV3jY6BHTPJOWZOsmrN.xCCVTxDGRWWaeQeB2VTHpQo7Ba5.o5C',
    courses: [],
    userType: 'Teacher',
    phone: '+84-855-574-073',
    gender: 'Nữ',
    shortBio: '<p>Hiện tại đang l&agrave; Gi&aacute;m Đốc Điều H&agrave;nh Navigos Search thuộc tập đo&agrave;n Navigos<br />Hơn 25 năm kinh nghiệm, trong đ&oacute; c&oacute; 20 năm trong lĩnh vực ph&aacute;t triển kinh doanh v&agrave; điều h&agrave;nh doanh nghiệp với gần 10 năm trong lĩnh vực Nh&acirc;n sự. <br />Trước khi gia nhập Navigos, chị đươc biết đến với c&aacute;c vai tr&ograve;:<br />Trưởng văn ph&ograve;ng đại diện đầu ti&ecirc;n tại Việt Nam của Hiệp hội kế to&aacute;n c&ocirc;ng chứng Anh Quốc ACCA<br />Gi&aacute;m đốc ph&aacute;t triển kinh doanh của Deloitte Việt Nam<br />Tổng gi&aacute;m đốc của eSillicon Việt Nam</p>',
  }, {
    email: 'truongphucanh@gmail.com',
    name: 'Trương Phúc Anh',
    bthday: new Date('1992-08-20'),
    password: '$2b$10$gc7DdySTp7qW5T3qm6y99OtQ6nfusnf5RWQsVoaWOZMzvm2LJiFha',
    courses: [],
    userType: 'Teacher',
    phone: '+84-555-588-560',
    gender: 'Nam',
    shortBio: '<p>- CEO Học viện Marketing Quốc tế TikTokVIP<br />- 5 năm kinh nghiệm l&agrave;m việc tại thị trường c&ocirc;ng nghệ Trung Quốc<br />- Được đ&agrave;o tạo chuy&ecirc;n s&acirc;u từ Douyin Trung Quốc trong 3 năm (Douyin l&agrave; cha đẻ của TikTok)<br />- Người cố vấn đứng sau th&agrave;nh c&ocirc;ng của h&agrave;ng loạt c&aacute;c Tiktoker, k&ecirc;nh tiktok Triệu follow như L&ecirc; Ch&iacute; Linh, Thiết Kế Elkey, CEO Trần Oanh, B&ugrave;i Tiến Dũng<br />- Hơn 1 năm đ&agrave;o tạo, tư vấn chiến lược kinh doanh tr&ecirc;n TikTok<br />- Người tạo n&ecirc;n tr&agrave;o lưu TikTok Business</p>',
  }, {
    email: 'nguyenbichtuyet@gmail.com',
    name: 'Nguyễn Bích Tuyết',
    bthday: new Date('1992-09-22'),
    password: '$2b$10$SC4f/inuSFwxbCeO1fh0hu75v2fXnyNrRhp7v0vTiZKuEC1vDuTUG',
    courses: [],
    userType: 'Teacher',
    phone: '+84-355-599-124',
    gender: 'Nữ',
    shortBio: '',
  }, {
    email: 'lethihonganh@gmail.com',
    name: 'Lê Thị Hồng Ánh',
    bthday: new Date('1979-03-23'),
    password: '$2b$10$ixxXy9G/RseClaEyBIZuye6Ag3MZg8i800U9Ipuqhe2LS7wnHu1Du',
    courses: [],
    userType: 'Teacher',
    phone: '+84-755-573-570',
    gender: 'Nữ',
    shortBio: '<p>Hiện tại đang l&agrave; Gi&aacute;m Đốc Điều H&agrave;nh Navigos Search thuộc tập đo&agrave;n Navigos<br />Hơn 25 năm kinh nghiệm, trong đ&oacute; c&oacute; 20 năm trong lĩnh vực ph&aacute;t triển kinh doanh v&agrave; điều h&agrave;nh doanh nghiệp với gần 10 năm trong lĩnh vực Nh&acirc;n sự. <br />Trước khi gia nhập Navigos, chị đươc biết đến với c&aacute;c vai tr&ograve;:<br />Trưởng văn ph&ograve;ng đại diện đầu ti&ecirc;n tại Việt Nam của Hiệp hội kế to&aacute;n c&ocirc;ng chứng Anh Quốc ACCA<br />Gi&aacute;m đốc ph&aacute;t triển kinh doanh của Deloitte Việt Nam<br />Tổng gi&aacute;m đốc của eSillicon Việt Nam</p>',
  }, {
    email: 'tranlevy@gmail.com',
    name: 'Trần Lê Vy',
    bthday: new Date('1979-08-21'),
    password: '$2b$10$CaY1vOpBX2Jt/51DWXl5Wu26k4UhO8EiEKbgUZ5bbwPnLawBuPbDy',
    courses: [],
    userType: 'Teacher',
    phone: '+84-855-519-220',
    gender: 'Nữ',
    shortBio: '<p>Bằng c&aacute;i "T&Acirc;M" y&ecirc;u nghề v&agrave; t&acirc;m huyết truyền đạt kiến thức cho thế hệ sau, đ&atilde; từng đ&agrave;o tạo khoảng tr&ecirc;n dưới 3 ng&agrave;n học vi&ecirc;n hiện đ&atilde; v&agrave; đang tham gia c&ocirc;ng t&aacute;c trong c&aacute;c doanh nghiệp v&agrave; c&aacute;c tổ chức kinh tế ch&iacute;nh trị x&atilde; hội.</p><p>C&ugrave;ng với đ&oacute;, giảng vi&ecirc;n đ&atilde; nhận được h&agrave;ng ng&agrave;n đ&aacute;nh gi&aacute; cao l&agrave; người thầy giảng dạy c&oacute; t&acirc;m v&agrave; nhiệt huyết trong c&ocirc;ng việc cũng như định hướng phương ph&aacute;p tự học cho học vi&ecirc;n đạt được hiệu quả cao nhất c&oacute; thể ph&ugrave; hợp với năng lực của từng học vi&ecirc;n.</p><p>Đ&atilde; từng học tập tại Nhật Bản từ th&aacute;ng 8/2009 - 12/2009</p><p>Đ&atilde; từng&nbsp; học tập tại Trung Quốc từ th&aacute;ng 1/2010 - 8/2010.</p><p>Đ&atilde; từng sống học tập v&agrave; l&agrave;m việc tại Đ&agrave;i Loan từ năm 2011 - 2014&nbsp;</p>',
  }, {
    email: 'nguyengiaanhtu@gmail.com',
    name: 'Nguyên Gia Anh Tú',
    bthday: new Date('1984-02-17'),
    password: '$2b$10$58tOOrP32K27NomwTo2h4er767MDDHZ2ZbXUH9FxW/YADQ4rgMMwK',
    courses: [],
    userType: 'Teacher',
    phone: '+84-855-570-536',
    gender: 'Nữ',
    shortBio: '<p>Bằng c&aacute;i "T&Acirc;M" y&ecirc;u nghề v&agrave; t&acirc;m huyết truyền đạt kiến thức cho thế hệ sau, đ&atilde; từng đ&agrave;o tạo khoảng tr&ecirc;n dưới 3 ng&agrave;n học vi&ecirc;n hiện đ&atilde; v&agrave; đang tham gia c&ocirc;ng t&aacute;c trong c&aacute;c doanh nghiệp v&agrave; c&aacute;c tổ chức kinh tế ch&iacute;nh trị x&atilde; hội.</p><p>C&ugrave;ng với đ&oacute;, giảng vi&ecirc;n đ&atilde; nhận được h&agrave;ng ng&agrave;n đ&aacute;nh gi&aacute; cao l&agrave; người thầy giảng dạy c&oacute; t&acirc;m v&agrave; nhiệt huyết trong c&ocirc;ng việc cũng như định hướng phương ph&aacute;p tự học cho học vi&ecirc;n đạt được hiệu quả cao nhất c&oacute; thể ph&ugrave; hợp với năng lực của từng học vi&ecirc;n.</p><p>Đ&atilde; từng học tập tại Nhật Bản từ th&aacute;ng 8/2009 - 12/2009</p><p>Đ&atilde; từng&nbsp; học tập tại Trung Quốc từ th&aacute;ng 1/2010 - 8/2010.</p><p>Đ&atilde; từng sống học tập v&agrave; l&agrave;m việc tại Đ&agrave;i Loan từ năm 2011 - 2014&nbsp;</p>',
  }, {
    email: 'leduc@gmail.com',
    name: 'Lê Đức',
    bthday: new Date('1989-02-09'),
    password: '$2b$10$UIqDgiNZ61To16IBRlvYHOjYiRHN6RmW87UwZqZLlw8xBpSlY/KKy',
    courses: [],
    userType: 'Teacher',
    phone: '+84-355-589-871',
    gender: 'Nam',
    shortBio: '<p>Hiện tại đang l&agrave; Gi&aacute;m Đốc Điều H&agrave;nh Navigos Search thuộc tập đo&agrave;n Navigos<br />Hơn 25 năm kinh nghiệm, trong đ&oacute; c&oacute; 20 năm trong lĩnh vực ph&aacute;t triển kinh doanh v&agrave; điều h&agrave;nh doanh nghiệp với gần 10 năm trong lĩnh vực Nh&acirc;n sự. <br />Trước khi gia nhập Navigos, chị đươc biết đến với c&aacute;c vai tr&ograve;:<br />Trưởng văn ph&ograve;ng đại diện đầu ti&ecirc;n tại Việt Nam của Hiệp hội kế to&aacute;n c&ocirc;ng chứng Anh Quốc ACCA<br />Gi&aacute;m đốc ph&aacute;t triển kinh doanh của Deloitte Việt Nam<br />Tổng gi&aacute;m đốc của eSillicon Việt Nam</p>',
  }, {
    email: 'tranvantu@gmail.com',
    name: 'Trần Văn Tú',
    bthday: new Date('1991-10-10'),
    password: '$2b$10$RIs0PEgBJ2lXhIqPuvdML..3ZUflD3mFrOW35uLv9bvWF8c7MlW8m',
    courses: [],
    userType: 'Teacher',
    phone: '+84-355-562-907',
    gender: 'Nam',
    shortBio: '<p>- CEO Học viện Marketing Quốc tế TikTokVIP<br />- 5 năm kinh nghiệm l&agrave;m việc tại thị trường c&ocirc;ng nghệ Trung Quốc<br />- Được đ&agrave;o tạo chuy&ecirc;n s&acirc;u từ Douyin Trung Quốc trong 3 năm (Douyin l&agrave; cha đẻ của TikTok)<br />- Người cố vấn đứng sau th&agrave;nh c&ocirc;ng của h&agrave;ng loạt c&aacute;c Tiktoker, k&ecirc;nh tiktok Triệu follow như L&ecirc; Ch&iacute; Linh, Thiết Kế Elkey, CEO Trần Oanh, B&ugrave;i Tiến Dũng<br />- Hơn 1 năm đ&agrave;o tạo, tư vấn chiến lược kinh doanh tr&ecirc;n TikTok<br />- Người tạo n&ecirc;n tr&agrave;o lưu TikTok Business</p>',
  }, {
    email: 'huynhphananh@gmail.com',
    name: 'Huỳnh Phan Anh',
    bthday: new Date('1978-07-31'),
    password: '$2b$10$h0wa2NxYfAwr8yYvSlUnDeJB2u54jHwlfD9KirMnVji4U/Yqkukee',
    courses: [],
    userType: 'Teacher',
    phone: '+84-755-565-329',
    gender: 'Nam',
    shortBio: '<p>Bằng c&aacute;i "T&Acirc;M" y&ecirc;u nghề v&agrave; t&acirc;m huyết truyền đạt kiến thức cho thế hệ sau, đ&atilde; từng đ&agrave;o tạo khoảng tr&ecirc;n dưới 3 ng&agrave;n học vi&ecirc;n hiện đ&atilde; v&agrave; đang tham gia c&ocirc;ng t&aacute;c trong c&aacute;c doanh nghiệp v&agrave; c&aacute;c tổ chức kinh tế ch&iacute;nh trị x&atilde; hội.</p><p>C&ugrave;ng với đ&oacute;, giảng vi&ecirc;n đ&atilde; nhận được h&agrave;ng ng&agrave;n đ&aacute;nh gi&aacute; cao l&agrave; người thầy giảng dạy c&oacute; t&acirc;m v&agrave; nhiệt huyết trong c&ocirc;ng việc cũng như định hướng phương ph&aacute;p tự học cho học vi&ecirc;n đạt được hiệu quả cao nhất c&oacute; thể ph&ugrave; hợp với năng lực của từng học vi&ecirc;n.</p><p>Đ&atilde; từng học tập tại Nhật Bản từ th&aacute;ng 8/2009 - 12/2009</p><p>Đ&atilde; từng&nbsp; học tập tại Trung Quốc từ th&aacute;ng 1/2010 - 8/2010.</p><p>Đ&atilde; từng sống học tập v&agrave; l&agrave;m việc tại Đ&agrave;i Loan từ năm 2011 - 2014&nbsp;</p>',
  }, {
    email: 'phamdat@gmail.com',
    name: 'Phạm Quốc Đạt',
    bthday: new Date('1981-05-20'),
    password: '$2b$10$OmlpS2jM/uX/vWHy2kDP7.Jc9hn/zmGo0LaS43OAt8lf8S7KaE0bG',
    courses: [],
    userType: 'Teacher',
    phone: '+84-355-509-262',
    gender: 'Nam',
    shortBio: '<p>Bằng c&aacute;i "T&Acirc;M" y&ecirc;u nghề v&agrave; t&acirc;m huyết truyền đạt kiến thức cho thế hệ sau, đ&atilde; từng đ&agrave;o tạo khoảng tr&ecirc;n dưới 3 ng&agrave;n học vi&ecirc;n hiện đ&atilde; v&agrave; đang tham gia c&ocirc;ng t&aacute;c trong c&aacute;c doanh nghiệp v&agrave; c&aacute;c tổ chức kinh tế ch&iacute;nh trị x&atilde; hội.</p><p>C&ugrave;ng với đ&oacute;, giảng vi&ecirc;n đ&atilde; nhận được h&agrave;ng ng&agrave;n đ&aacute;nh gi&aacute; cao l&agrave; người thầy giảng dạy c&oacute; t&acirc;m v&agrave; nhiệt huyết trong c&ocirc;ng việc cũng như định hướng phương ph&aacute;p tự học cho học vi&ecirc;n đạt được hiệu quả cao nhất c&oacute; thể ph&ugrave; hợp với năng lực của từng học vi&ecirc;n.</p><p>Đ&atilde; từng học tập tại Nhật Bản từ th&aacute;ng 8/2009 - 12/2009</p><p>Đ&atilde; từng&nbsp; học tập tại Trung Quốc từ th&aacute;ng 1/2010 - 8/2010.</p><p>Đ&atilde; từng sống học tập v&agrave; l&agrave;m việc tại Đ&agrave;i Loan từ năm 2011 - 2014&nbsp;</p>',
  }, {
    email: 'dinhnongmanh@gmail.com',
    name: 'Đinh Nông Mạnh',
    bthday: new Date('1982-09-08'),
    password: '$2b$10$Pry0fjbUC5No4hKirI9BnuvZZiLkFqm8nB5zrWKOJ60M0y3xV7Gce',
    courses: [],
    userType: 'Teacher',
    phone: '+84-755-521-610',
    gender: 'Nam',
    shortBio: '<p>- CEO Học viện Marketing Quốc tế TikTokVIP<br />- 5 năm kinh nghiệm l&agrave;m việc tại thị trường c&ocirc;ng nghệ Trung Quốc<br />- Được đ&agrave;o tạo chuy&ecirc;n s&acirc;u từ Douyin Trung Quốc trong 3 năm (Douyin l&agrave; cha đẻ của TikTok)<br />- Người cố vấn đứng sau th&agrave;nh c&ocirc;ng của h&agrave;ng loạt c&aacute;c Tiktoker, k&ecirc;nh tiktok Triệu follow như L&ecirc; Ch&iacute; Linh, Thiết Kế Elkey, CEO Trần Oanh, B&ugrave;i Tiến Dũng<br />- Hơn 1 năm đ&agrave;o tạo, tư vấn chiến lược kinh doanh tr&ecirc;n TikTok<br />- Người tạo n&ecirc;n tr&agrave;o lưu TikTok Business</p>',
  }, {
    email: 'vuthitrang@gmail.com',
    name: 'Vũ Thị Trang',
    bthday: new Date('1991-01-16'),
    password: '$2b$10$vfTth8ptjJKAYQT02G.CIec4g7Jnz1PKvrOQBPESYxwE/qWceNYW.',
    courses: [],
    userType: 'Teacher',
    phone: '+84-555-545-500',
    gender: 'Nữ',
    shortBio: '<p>Hiện tại đang l&agrave; Gi&aacute;m Đốc Điều H&agrave;nh Navigos Search thuộc tập đo&agrave;n Navigos<br />Hơn 25 năm kinh nghiệm, trong đ&oacute; c&oacute; 20 năm trong lĩnh vực ph&aacute;t triển kinh doanh v&agrave; điều h&agrave;nh doanh nghiệp với gần 10 năm trong lĩnh vực Nh&acirc;n sự. <br />Trước khi gia nhập Navigos, chị đươc biết đến với c&aacute;c vai tr&ograve;:<br />Trưởng văn ph&ograve;ng đại diện đầu ti&ecirc;n tại Việt Nam của Hiệp hội kế to&aacute;n c&ocirc;ng chứng Anh Quốc ACCA<br />Gi&aacute;m đốc ph&aacute;t triển kinh doanh của Deloitte Việt Nam<br />Tổng gi&aacute;m đốc của eSillicon Việt Nam</p>',
  }
]

module.exports = {
    user_data: user_data,
    course_data: course_data,
    category_data: category_data,
    teacher_data: teacher_data,
};