const user_data = [{
    email: "lethanhviet@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$V1jAu/3HNMfwZtglX/cIWeSCC5c.TdD5DNbKBhnpT8fNZSoT9H3zq",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$.AZaZEJYMb6RoyWd2e6nnu7zLtdjDBvsPh2ZKSxjWyNeKayiSIuTO",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$SsrMARwOZQrKPzHW8m98POpponroVL7paSAOlgxsjXKcQD6nFa8ja",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$bsjPRJi8ffjGkFwNW.tFdueCyE/dhfwZLZnkksE4j4zNp/DWqdRcS",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$jr7WUFYSiLTQFCCj4B07juS8zVO/5FowRxEfVOzWrQ.WXjRqS7lse",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$GA04eMQFQM4wGan4/GqKHeEsK.zo/pkYMZvNf93r1Cxrl6nk9Fci6",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$n8xPTrCgzd5rZTRoiA8DxOz8JNJdPgly/xyLYeR2r1NWYsn8gsJZa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$CxWIg6pz9CEhSkiPIzBPc.rasGX3rkBbiHBf93faMgky7.AE8lxeK",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$074w/cGELvGdh9UjjeiOXuYfuHC692BBznhcwCEy2./IwSkgFU1Zm",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$gaF5nvAkRAidOJSVQ5Q6GuW.vUsRlsVem8aI50fbtP94HS/wZe.ni",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$4g.UqmdO6J7ZLN2CuKWL0ew5tJzke5Rg2e0p5WjrjoiRrS3ihdvma",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$LU6/U0c7N1.6FB13.t1uveboCA3CKuMFymKgbJXmCpipy43r0Y.Iq",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$WwCMbJfnv9bITwAb2ibnJ.xEp37kAUzT2aQEpmiM8qDqNs91xNp.O",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$iDdpW.dzqzbV5B5glszhUesu5SG4robO40JmbiZFhIur8d3gzefim",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet1@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$lO1uF7DwriEa/GcRvcUcXuPyN7D1cLzm8CVRRx7jp/uFp5rhUBliS",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh1@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$nkIAif5nkULprjqA7wDAj.RmKhX7ifZXIphuEqRn2v2IKeS/a6ZUy",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong1@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$E9qYfgiN7A1/2e4OJpZhSuPL8dO4B45sPxZF7gftLKsT/ZyWvtiWC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy1@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$lXTFqzYxk3Whia//gNgIVOGArSMKned84fopI9Pr0abQMYpIBRzoC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong1@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$mR6iqNZ.RpDg82AJbCNcc.ibCkrOcxbFEM9RWfnVDqFQMz1w1HIya",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung1@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$H0mYU.DaOX8IJoMxXnmmNObQtN7VsMrPJjDBCdXBcYXSFy4rsuLIC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh1@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$.8Pq0I4J.oyPqZFfVPqUr.w938hzJvMgHj5pdaB.36ErWyDhWIe7m",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen1@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$xuPi05oEOZHv/dOlFPnieu.sNYAZ6PkSeDe.e2aE2zMVp4p79d3WC",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi1@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$pGHzG9u5aIHb4cohGSLtCeoS4v5MdXHCAyYuGzfNsIj5uvnK0pFMi",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan1@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$DwX2ZwhJdYMia2TPM3WVAOfCDXifEsC2xMpWtLzy2/cEpWWeh8d7q",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy1@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$sKpDFgI9N0KfMa24kQNvP.oopa0C6nrsZW1A74rSrIccB/nM4T0hS",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi1@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$QX0Ugd..8YVkRRhNAMYeie0D/SYEIuaP7GRRiF6fNFfEe2SKwId32",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan1@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$OTPKkDGbcSL1/WW/9k6D2OoF8gtcF/uILMKNOizhBbF0D4ZzMpbiO",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh1@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$fKiyfZviWMkfWT/7rIR/z.5s9Abj2d/haL4SOIrLT3NBaPImAaSPe",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet2@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$VeaWctGcLeTN18p9Lba2X.rAMYf0l7lbEMq0yY8BX7lxjRZPUBGJe",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh2@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong2@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy2@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong2@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung2@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh2@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen2@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi2@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan2@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy2@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi2@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan2@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh2@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet3@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh3@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong3@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy3@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong3@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung3@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh3@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen3@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi3@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan3@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy3@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi3@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan3@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh3@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet4@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh4@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong4@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy4@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong4@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung4@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh4@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen4@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi4@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan4@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy4@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi4@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan4@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh4@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "lethanhviet5@gmail.com",
    name: "Lê Thành Việt",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "giavinh5@gmail.com",
    name: "Võ Trọng Gia Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vantruong5@gmail.com",
    name: "Nguyễn Văn Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thanhuy5@gmail.com",
    name: "Bùi Thanh Uy",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "quangtruong5@gmail.com",
    name: "Lê Huỳnh Quang Trường",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "trantrung5@gmail.com",
    name: "Nguyễn Trần Trung",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongvinh5@gmail.com",
    name: "Phạm Hồng Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "hongxuyen5@gmail.com",
    name: "Đặng Thị Hồng Xuyên",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thinhi5@gmail.com",
    name: "Huỳnh Thị Nhi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "vietxuan5@gmail.com",
    name: "Phạm Viết Xuân",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "bichthuy5@gmail.com",
    name: "Nguyễn Thị Bích Thủy",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "thivi5@gmail.com",
    name: "Huỳnh Thị Vi",
    gender: "Nữ",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "nhattuan5@gmail.com",
    name: "Lê Nhật Tuấn",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}, {
    email: "tanvinh5@gmail.com",
    name: "Nguyễn Tân Vinh",
    gender: "Nam",
    phone: "0902794731",
    password: "$2b$10$MOjaZpYw6InFbI61nJvQweenvFE1RmazIviLjLzFocdBpxjtY.RBa",
    fbID: "",
    ggID: "",
    isValidated: true,
    OTP: null,
    bthday: null,
    courses: [],
    userType: "Student",
    watchList: [],
    cart: []
}];

const course_data = [
    {
        name: 'NodeJS cho người mới bắt đầu',
        category: 'Lập trình Web',
        chapters: [
            {
                title: 'Bài 1: Giới thiệu những kiến thức cơ bản về NodeJS',
                video: '/courses/temp/0.mp4',
            },
            {
                title: 'Bài 2: NPM và Package',
                video: '/courses/temp/1.mp4',
            },
            {
                title: 'Bài 3: Install and Uninstall package',
                video: '/courses/temp/2.mp4',
            },
        ],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,20),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản nhất cho người mới học NodeJS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0.2,
        thumbnail: '/images/courses_thumbnail/1.jpg',
        description: `NodeJS là một mã nguồn mở, được dùng để xây dựng các ứng dụng mạng, đặc biệt các ứng đòi hỏi real time (thời gian thực) & khối lượng request lớn. Chúng ta có thể lập trình NodeJS với ngôn ngữ JavaScript. NodeJS có thể được dùng để xây dựng hoàn chỉnh một trang web, ngoài ra, NodeJS còn có thể tích hợp để xây dựng các ứng dụng real time trên iOS, Android, Game online với Unity, Cocos2dx.
                Về tốc độ thực thi, Node.js có thể nói là nhanh nhất hiện nay, hơn cả java. Bởi lẽ node.js kế thừa công nghệ V8 của google, khả năng tự build server bằng ngôn ngữ client giúp cho việc trung chuyển dữ liệu diễn ra nhanh hơn. Đồng thời giảm khả năng rủi ro bị ngắt (interupt). Ngoài ra nhờ cơ chế Non I/O Blocking, tận dụng tối đa tài nguyên của server, không tạo ra độ trễ như các ngôn ngữ phía server khác.
                NodeJS thực sự tỏa sáng trong việc xây dựng RESTful API (JSON). Gần như không có ngôn ngữ nào xử lý JSON dễ dàng hơn Javascript, chưa kể các API server thường không phải thực hiện những xử lý nặng nề nhưng lượng concurrent request thì rất cao. Mà Node.js thì xử lý non-blocking. Chẳng còn gì thích hợp hơn Node.js trong trường hợp này!
                NodeJS sinh ra là để xây dựng các ứng dụng thời gian thực (Real time) như ứng dụng chat, các dịch vụ mạng xã hội như Facebook, Twitter,…
                Đối với thiết kế web: NodeJS xử lý mọi request trên cùng một process giúp cho việc xây dựng các bộ nhớ đệm chưa bao giờ đơn giản đến thế: Node.js có thể handle hàng nghìn kết nối đồng thời với chi phí tối thiểu trên 1 quá trình duy nhất.
                NodeJS sử dụng ngôn ngữ JavaScript - một ngôn ngữ phổ biến, và chính điều này đã giúp node.js trở nên quen thuộc và dễ dàng được áp dụng rộng rãi hơn.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Sau khi kết thúc khóa học bạn sẽ có những kiến thức cơ bản nhất về NodeJS, đủ kiến thức để xây dựng những web thương mại điện tử bằng NodeJS và ứng tuyển thực tập về NodeJS ở các công ty.',
    },{
        name: 'Khóa học Full-stack web developer',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,19),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học bao gồm nhiều kỹ năng cả về FE và BE : HTML, CSS, JS, NodeJS, AngularJS,...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/2.jpg',
        description: `Khóa học cung cấp những kiến thức và nền tảng cơ bản nhất cả về Front-end lẫn Back-end cho học viên.
         Về front-end, các bạn sẽ được học cơ bản từ HTML, CSS, responsive,... tiếp đến là JS và ES6,ES7, ES2020,...
         Ngoài ra khóa học còn cung cấp kiến thức về các frameword của JavaScript như ReactJS, AngularJS, VueJS hỗ trợ
         lập trình về client-side. Về Back-end, các bạn sẽ được học cách tạo server, sử dụng CSDL, deploy, CICD,...Trong khóa học này
         chúng ta sẽ sử dụng NodeJS ở server-side và Express là chủ yếu, về Cơ sở dũ liệu, bạn học sẽ được hướng dẫn sử dụng MySQL,
         và No-SQL MongoDB. Ngoài ra khóa học cũng sẽ hướng dẫn hoàn thành một Project hoàn chỉnh về một trang thương mại điện tử, đồng
         thời cũng hướng dẫn bạn học deploy website của mình lên Heroku.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: `Sau khi kết thúc khóa học các bạn sẽ có một nền tảng vững chắc để trở thành một Full-stack developer.
        Có đầy đủ kiến thức về Front-end và Back-end để ứng tuyển thực tập ở các công ty.`,
    },{
        name: 'Khóa học NodeJS chuyên sâu',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,17),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học chuyên sâu về SSR với NodeJS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/3.jpg',
        description: `NodeJS là một mã nguồn mở, được dùng để xây dựng các ứng dụng mạng, đặc biệt các ứng đòi hỏi real time (thời gian thực) & khối lượng request lớn. Chúng ta có thể lập trình NodeJS với ngôn ngữ JavaScript. NodeJS có thể được dùng để xây dựng hoàn chỉnh một trang web, ngoài ra, NodeJS còn có thể tích hợp để xây dựng các ứng dụng real time trên iOS, Android, Game online với Unity, Cocos2dx.
        Về tốc độ thực thi, Node.js có thể nói là nhanh nhất hiện nay, hơn cả java. Bởi lẽ node.js kế thừa công nghệ V8 của google, khả năng tự build server bằng ngôn ngữ client giúp cho việc trung chuyển dữ liệu diễn ra nhanh hơn. Đồng thời giảm khả năng rủi ro bị ngắt (interupt). Ngoài ra nhờ cơ chế Non I/O Blocking, tận dụng tối đa tài nguyên của server, không tạo ra độ trễ như các ngôn ngữ phía server khác.
        NodeJS thực sự tỏa sáng trong việc xây dựng RESTful API (JSON). Gần như không có ngôn ngữ nào xử lý JSON dễ dàng hơn Javascript, chưa kể các API server thường không phải thực hiện những xử lý nặng nề nhưng lượng concurrent request thì rất cao. Mà Node.js thì xử lý non-blocking. Chẳng còn gì thích hợp hơn Node.js trong trường hợp này!
        NodeJS sinh ra là để xây dựng các ứng dụng thời gian thực (Real time) như ứng dụng chat, các dịch vụ mạng xã hội như Facebook, Twitter,…
        Đối với thiết kế web: NodeJS xử lý mọi request trên cùng một process giúp cho việc xây dựng các bộ nhớ đệm chưa bao giờ đơn giản đến thế: Node.js có thể handle hàng nghìn kết nối đồng thời với chi phí tối thiểu trên 1 quá trình duy nhất.
        NodeJS sử dụng ngôn ngữ JavaScript - một ngôn ngữ phổ biến, và chính điều này đã giúp node.js trở nên quen thuộc và dễ dàng được áp dụng rộng rãi hơn.
        Đây là khóa học nối tiếp của khóa học NodeJS cho người mới bắt đầu, sau khi đã có những kiến thức cơ bản 
        chúng ta sẽ tiếp tục tìm hiểu những kiến thức nâng cao hơn về NodeJS. Trong khóa học này bạn sẽ được học về Filesystem,
         Module, Deloy, Authentication,...`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Hoàn thiện và nâng cao kiến thức về NodeJS',
    },{
        name: 'Khóa học MERN: MongoDB, Express, ReactJS, NodeJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học full-stack với MongoDB database và các framework của JS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/4.jpg',
        description: `Khóa học full-stack với MongoDB database và các framework của JS. Trong khóa học này, bạn học sẽ được cung
        cấp những kiến thức cần thiết để tạo một website thương mại điện tử  với MERN: M - MongoBD, E - Express, R - ReacJS, N - NodeJS.
        Khóa học sẽ hướng dẫn bạn sử dụng NodeJS + Express để tạo một server và chạy trên chính máy tính của mình; sử dụng ReactJS để 
        code giao diện ở client-side, bên cạnh kiến thức cơ bản về React như Component, Router, ... khóa học còn cung cấp kiến thức về 
        Hook, Redux,...; cơ sở dữ liệu được dùng trong khóa học này như đã đề cập ở trên chính là MongoDB - một No-SQL.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Hiểu biết về 4 thành phần của MEAN, có khả năng tự lập trình các website sử dụng những kiến thức đã học.',
    },{
        name: 'Khóa học MEAN: MongoDB, Express, AngularJS, NodeJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học full-stack với MongoDB database và các framework của JS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/5.png',
        description: `Khóa học full-stack với MongoDB database và các framework của JS. Trong khóa học này, bạn học sẽ được cung
        cấp những kiến thức cần thiết để tạo một website thương mại điện tử  với MERN: M - MongoBD, E - Express, R - ReacJS, N - NodeJS.
        Khóa học sẽ hướng dẫn bạn sử dụng NodeJS + Express để tạo một server và chạy trên chính máy tính của mình; sử dụng ReactJS để 
        code giao diện ở client-side, bên cạnh kiến thức cơ bản về React như Component, Router, ... khóa học còn cung cấp kiến thức về 
        Hook, Redux,...; cơ sở dữ liệu được dùng trong khóa học này như đã đề cập ở trên chính là MongoDB - một No-SQL.`,
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: 'Hiểu biết về 4 thành phần của MEAN, có khả năng tự lập trình các website sử dụng những kiến thức đã học.',
    },{
        name: 'Javascript Framework: ReactJS and AngularJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản và đầy đủ về 2 framework phổ biến của JS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/6.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học GraphQL',
        category: 'Hệ thống thông tin',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học về cơ sở GraphQL và tích hợp SSR',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/7.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học lập trình Web cơ bản',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản về HTML, CSS, JavaScript,...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/8.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học ExpressJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Express là một framework của JS sử dụng ở SS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/9.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học React cơ bản',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản về React: Component, Router, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/10.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Javascript cơ bản',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học cơ bản về JS: ES5, ES6, variable, operations, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/11.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Javascript nâng cao',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học nâng cao về JS: hoisting, scope, promise, async await, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/12.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Javascript ES6',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học về JS phiên bản ES6: let, arrow function, spread operator, ...',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/13.png',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Khóa học NuxtJS',
        category: 'Hệ thống thông tin',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Khóa học dành cho người mới bắt đầu về framework NuxtJS',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/14.jpeg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },{
        name: 'Lập trình web với NodeJS',
        category: 'Lập trình Web',
        chapters: [],
        rate: [0,0,0,0,0],
        lastModified: Date.now(),
        createdDate: new Date(2020,10,22),
        price: 200,
        teacher: '',
        students: 0,
        briefDes: 'Lập trình SS với NodeJS nâng cao',
        views: 0,
        soldInWeek: 0,
        saleOff: 0,
        thumbnail: '/images/courses_thumbnail/15.jpg',
        description: '',
        commands: ['Có hiểu biết cơ bản về lập trình', 
        'Hiểu biết cơ bản về cấu trúc dữ liệu và giải thuật, các kiểu dữ liệu đơn giản',
        'Có khả năng đọc hiểu tài liệu tiếng anh sẽ được cung cấp trong khóa học'],
        target: '',
    },
]

const category_data = [
    {
        name: 'Công nghệ thông tin',
        parent: 'null',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Toán học',
        parent: 'null',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Lập trình Web',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Lập trình ứng dụng di động',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Khoa học máy tính',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Hệ thống thông tin',
        parent: 'Công nghệ thông tin',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Toán tổ hợp',
        parent: 'Toán học',
        courses: '',
        soldInWeek: 0
    },
    {
        name: 'Toán rời rạc',
        parent: 'Toán học',
        courses: '',
        soldInWeek: 0
    },

    {
        name: 'Xác suất thống kê',
        parent: 'Toán học',
        courses: '',
        soldInWeek: 0
    }
]

const teacher_data = [{
    email: 'nguyenvantu5@gmail.com',
    name: 'Nguyễn Văn Tú',
    bthday: null,
    password: '$2b$10$Fd0GDCRSSwpzsUaaAzSrz.tLxvBIWWX4G1WwRmekSvK7UdrS94z7a',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'trantanthanh2@gmail.com',
    name: 'Trần Tấn Thành',
    bthday: null,
    password: '$2b$10$gzYEFuBiuRsv51yy9zxRZur.mbAPN7DBBLHRSZwY4aEhyTwJl/9iW',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'phamnguyencongminh@gmail.com',
    name: 'Phạm Nguyễn Công Minh',
    bthday: null,
    password: '$2b$10$qk7zGEBjc1uNHtgg8.qcQO6ezLLJ85awi6b6cB6G3L3YTp4Uwzfnq',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'tranlecongluat@gmail.com',
    name: 'Trần Lê Công Luật',
    bthday: null,
    password: '$2b$10$FHwKig1gVky2zPmFtiXcsOnYf25BLnarl/NPQC6aDJN8LfbY3SlXS',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'nguyenletuananh@gmail.com',
    name: 'Nguyên Lê Tuấn Anh',
    bthday: null,
    password: '$2b$10$S9Cmb4KBjjXWkoqHNIz9NeI7H7gu0e/LwsyF94Gv2t0xptdbw9naS',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'lethanhbinh@gmail.com',
    name: 'Lê Thanh Bình',
    bthday: null,
    password: '$2b$10$QC2iZAwoXFUIUb/a/OK0nOmF/FPeUoizQ5QohngAvfzypGhNSUmSO',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'phamtandung@gmail.com',
    name: 'Phạm Tấn Dũng',
    bthday: null,
    password: '$2b$10$N3Z0kfgwW82xC7Vl8DxfN.WnJ8JwmeJmVmm3TyQREwMNUcUba1OG.',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'tranphutrong@gmail.com',
    name: 'Trần Phú Trọng',
    bthday: null,
    password: '$2b$10$k6RGJS0f5GIZVHwVTkokRuhGpGuG9dEGPNX9knxhHAQ6QV2mvkYmi',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'nguyentrankimngan@gmail.com',
    name: 'Nguyễn Trần Kim Ngân',
    bthday: null,
    password: '$2b$10$nYYV3jY6BHTPJOWZOsmrN.xCCVTxDGRWWaeQeB2VTHpQo7Ba5.o5C',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nữ',
  }, {
    email: 'truongphucanh@gmail.com',
    name: 'Trương Phúc Anh',
    bthday: null,
    password: '$2b$10$gc7DdySTp7qW5T3qm6y99OtQ6nfusnf5RWQsVoaWOZMzvm2LJiFha',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'nguyenbichtuyet@gmail.com',
    name: 'Nguyễn Bích Tuyết',
    bthday: null,
    password: '$2b$10$SC4f/inuSFwxbCeO1fh0hu75v2fXnyNrRhp7v0vTiZKuEC1vDuTUG',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nữ',
  }, {
    email: 'lethihonganh@gmail.com',
    name: 'Lê Thị Hồng Ánh',
    bthday: null,
    password: '$2b$10$ixxXy9G/RseClaEyBIZuye6Ag3MZg8i800U9Ipuqhe2LS7wnHu1Du',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nữ',
  }, {
    email: 'tranlevy@gmail.com',
    name: 'Trần Lê Vy',
    bthday: null,
    password: '$2b$10$CaY1vOpBX2Jt/51DWXl5Wu26k4UhO8EiEKbgUZ5bbwPnLawBuPbDy',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nữ',
  }, {
    email: 'nguyengiaanhtu@gmail.com',
    name: 'Nguyên Gia Anh Tú',
    bthday: null,
    password: '$2b$10$58tOOrP32K27NomwTo2h4er767MDDHZ2ZbXUH9FxW/YADQ4rgMMwK',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nữ',
  }, {
    email: 'leduc@gmail.com',
    name: 'Lê Đức',
    bthday: null,
    password: '$2b$10$UIqDgiNZ61To16IBRlvYHOjYiRHN6RmW87UwZqZLlw8xBpSlY/KKy',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'tranvantu@gmail.com',
    name: 'Trần Văn Tú',
    bthday: null,
    password: '$2b$10$RIs0PEgBJ2lXhIqPuvdML..3ZUflD3mFrOW35uLv9bvWF8c7MlW8m',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'huynhphananh@gmail.com',
    name: 'Huỳnh Phan Anh',
    bthday: null,
    password: '$2b$10$h0wa2NxYfAwr8yYvSlUnDeJB2u54jHwlfD9KirMnVji4U/Yqkukee',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'phamdat@gmail.com',
    name: 'Phạm Quốc Đạt',
    bthday: null,
    password: '$2b$10$OmlpS2jM/uX/vWHy2kDP7.Jc9hn/zmGo0LaS43OAt8lf8S7KaE0bG',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'dinhnongmanh@gmail.com',
    name: 'Đinh Nông Mạnh',
    bthday: null,
    password: '$2b$10$Pry0fjbUC5No4hKirI9BnuvZZiLkFqm8nB5zrWKOJ60M0y3xV7Gce',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nam',
  }, {
    email: 'vuthitrang@gmail.com',
    name: 'Vũ Thị Trang',
    bthday: null,
    password: '$2b$10$vfTth8ptjJKAYQT02G.CIec4g7Jnz1PKvrOQBPESYxwE/qWceNYW.',
    courses: [],
    userType: 'Teacher',
    phone: '',
    gender: 'Nữ',
  }
]

module.exports = {
    user_data: user_data,
    course_data: course_data,
    category_data: category_data,
    teacher_data: teacher_data,
};